### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/python-novice-inflammation#640]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [ ] Example code chunks run as expected
- [ ] Challenges / exercises run as expected
- [ ] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [ ] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
Hi Maintainers! - Just confirming that you're still planning on including your lesson in the June 2019 release. We'll be putting out a blog post tomorrow inviting contributors to work on issues that have been tagged as part of the release milestone, so if there are specific issues you're looking for community help with, please add them to that milestone. I'll make a first pass and add issues that are currently marked "help-wanted" to the milestone, but please feel free to update the milestone issue list at your convenience. Please let me know if you have any questions!

**Comment by annefou** [comment]
Ye we do. Hope we are still on time.

**Comment by ErinBecker** [comment]
Hey Maintainers - just checking in to see if you're still planning on joining the release this month. We're asking that all lessons have completed the checklist by [Tuesday, 4 June, Anywhere on Earth time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20190604T235959&p1=3399) in order to be included in the release. Please let me and @fmichonneau know if you have any questions or are running into any technical issues with preparing your lesson.

**Comment by maxim-belkin** [comment]
@annefou, what do you think about the release? (My understanding is that we missed it.) 
I'm OK with skipping this release given that we've got a few things on the to-do list (change language in the episodes, verify a few things). If you're OK with skipping this release, we can proceed as usual. If you'd like to push for a release, all we really have to do is streamline the PR on demotivating language and fix links (links to references don't work in locally-rendered versions --related to https://github.com/carpentries/styles/issues/410).

**Comment by annefou** [comment]
Yes I guess we missed it. I am also OK with skipping this release. Sorry for not being more responsive!

**Comment by maxim-belkin** [comment]
There is nothing to apologize for. I suggest that we close this issue and create a new one with similar but extended checklist.

**Comment by annefou** [comment]
It sounds like a good plan! Thanks!

**Comment by maxim-belkin** [comment]
Superseded by swcarpentry/python-novice-inflammation#655

**Comment by ErinBecker** [comment]
Thank you @maxim-belkin and @annefou for all of your work on this. No problem with delaying to the next release. Please let me know if you need anything.
