### ISSUE TITLE
Checklist for the next lesson release

### ISSUE THREAD

**Issue by maxim-belkin** [swcarpentry/python-novice-inflammation#655]
This issue supersedes swcarpentry/python-novice-inflammation#640

@annefou and I decided to skip June 2019 release of this lesson as there is a number of issues/PRs that we'd like to be resolved in the next release. Below is the original checklist for participating in June 2019 release. After the original list, we include a list of additional Pull Requests & Issues we'd like to be resolved (or closed, if obsolete) before the next release

- [ ] Example code chunks run as expected
- [ ] Challenges / exercises run as expected
- [ ] Challenge / exercise solutions are correct
- [x] Callout boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, ensure filenames are consistent)
- [x] Some Instructor notes are provided
- [ ] Lesson links work as expected (related to https://github.com/carpentries/styles/issues/410)

---

- [ ] Remove demotivating use of "just": swcarpentry/python-novice-imflammation#653 
- [ ] Evaluate the use of dismissive language in the lesson (For reference, see this [link](https://carpentries.github.io/instructor-training/03-expertise/#dismissive-language))
- [ ] Discuss the possibility of splitting intro to variables into a separate episode
- [ ] Switch lists and loops episodes (swcarpentry/python-novice-inflammation#496)
- [ ] Improve episode 1 (swcarpentry/python-novice-inflammation#543)

@annefou please feel free to add any other items I might've forgotten about.
